# Generated by Django 4.2.1 on 2023-06-04 09:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngo',
            name='accepted_food_items',
        ),
        migrations.RemoveField(
            model_name='ngo',
            name='delivery_time',
        ),
        migrations.RemoveField(
            model_name='ngo',
            name='received_donations',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='delivery_time',
        ),
        migrations.AddField(
            model_name='donation',
            name='confirmed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='donation',
            name='delivery_time',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='donation',
            name='posted',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Rest_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quatityRequested', models.IntegerField()),
                ('confirmed', models.BooleanField(default=True)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.donation')),
                ('food_items_donated', models.ManyToManyField(to='app1.fooditem')),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.ngo')),
            ],
        ),
    ]
