# Generated by Django 4.2.1 on 2023-06-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_ngo_accepted_food_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.RemoveField(
            model_name='donation',
            name='food_items_donated',
        ),
        migrations.RemoveField(
            model_name='rest_request',
            name='food_items_donated',
        ),
        migrations.AddField(
            model_name='donation',
            name='food_items_donated',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rest_request',
            name='food_items_donated',
            field=models.CharField(default='', max_length=255),
        ),
    ]
