# Generated by Django 4.2.1 on 2023-06-04 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_ngo_name_restaurant_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.IntegerField()),
                ('confirmed', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='donation',
            name='food_items_donated',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='stock',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='restaurant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='app1.restaurant'),
        ),
        migrations.DeleteModel(
            name='Rest_Request',
        ),
        migrations.AddField(
            model_name='restrequest',
            name='donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.donation'),
        ),
        migrations.AddField(
            model_name='restrequest',
            name='food_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.fooditem'),
        ),
        migrations.AddField(
            model_name='restrequest',
            name='ngo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.ngo'),
        ),
    ]
