# Generated by Django 4.2.1 on 2023-06-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_restrequest_remove_donation_food_items_donated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='food_items_donated',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='stock',
            field=models.ManyToManyField(related_name='restaurants', to='app1.fooditem'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='review',
            field=models.TextField(blank=True),
        ),
    ]
