# Generated by Django 4.2.1 on 2023-06-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_donation_food_items_donated_restaurant_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='food_items_donated',
        ),
        migrations.AddField(
            model_name='donation',
            name='food_items_donated',
            field=models.ManyToManyField(to='app1.fooditem'),
        ),
    ]
