# Generated by Django 4.2.1 on 2023-06-08 14:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_ngo_is_verified_restaurant_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='restrequest',
            name='donation',
        ),
        migrations.RemoveField(
            model_name='restrequest',
            name='food_item',
        ),
        migrations.RemoveField(
            model_name='restrequest',
            name='ngo',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='food_items_donated',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='posted',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='stock',
        ),
        migrations.AddField(
            model_name='donation',
            name='expiration_date',
            field=models.DateField(default=datetime.date(2023, 6, 11)),
        ),
        migrations.AddField(
            model_name='donation',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='ngo',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='donation',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donation',
            name='ngo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations_received', to='app1.ngo'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='app1.restaurant'),
        ),
        migrations.DeleteModel(
            name='FoodItem',
        ),
        migrations.DeleteModel(
            name='RestRequest',
        ),
        migrations.AddField(
            model_name='donationrequest',
            name='donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='app1.donation'),
        ),
        migrations.AddField(
            model_name='donationrequest',
            name='ngo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.ngo'),
        ),
    ]
