# Generated by Django 4.0.2 on 2023-06-08 20:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_donationrequest_remove_restrequest_donation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='delivery_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='donation',
            name='name',
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
    ]
