# Generated by Django 4.0.2 on 2023-06-08 21:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_donation_delivery_time_alter_donation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='expiration_date',
            field=models.DateField(default=datetime.date(2023, 6, 12)),
        ),
        migrations.AlterField(
            model_name='donation',
            name='name',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
