# Generated by Django 4.2.1 on 2023-06-11 18:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_donation_expiration_date_alter_donation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donation',
            name='expiration_date',
            field=models.DateField(default=datetime.date(2023, 6, 14)),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_requests', to='app1.donation'),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='ngo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_requests_received', to='app1.ngo'),
        ),
    ]
