# Generated by Django 4.0.2 on 2023-06-18 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_alter_donation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
