# Generated by Django 4.2.1 on 2023-06-20 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_alter_donation_donation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngo',
            name='category',
        ),
        migrations.RemoveField(
            model_name='ngo',
            name='review',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cuisine_type',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='donation',
            name='expiration_date',
            field=models.DateField(default=datetime.date(2023, 6, 23)),
        ),
    ]
