# Generated by Django 4.2.1 on 2023-06-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_remove_ngo_category_remove_ngo_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='ngo_profiles'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_profiles'),
        ),
    ]
